apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: fraud-app-event-listener
  labels:
    app: fraud-app-trigger
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - triggerRef: fraud-app-trigger